### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by ahtinurme** [vcian/pulse-active-sessions#13]
Getting this when trying to access dashboard:

`Division by zero {"view":{"view":"/home/forge/elux-admin.path.ee/vendor/vcian/pulse-active-sessions/resources/views/livewire/pulse_active_session.blade.php","data":[]},"userId":16779,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Division by zero at /home/forge/elux-admin.path.ee/vendor/vcian/pulse-active-sessions/resources/views/livewire/pulse_active_session.blade.php:30)`

**Comment by ahtinurme** [comment]
Seems to be because I'm using "redis" as session driver, not "file" or "database".
I guess supporting session driver is "nice-to-have" feature, which I currently don't have time to implement, so I just made a PR for failing for using any other driver than "file" or "database": https://github.com/vcian/pulse-active-sessions/pull/14

**Comment by ruchit288** [comment]
- Issue resolved of "division by zero". 
- Also integrated Redis session drive feature.
