### ISSUE TITLE
Hardcoded App\Models\User in PulseActiveSessionRecorder

### ISSUE THREAD

**Issue by webard** [vcian/pulse-active-sessions#29]
Hello,

please make User model configurable or maybe take it from auth.php config. In many projects, User model is not in default namespace.

In my modularized project is:
```
 'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => Modules\User\Entities\User::class,
        ],
```

Thank you

**Comment by Xety** [comment]
Same problem here.

**Comment by ruchit288** [comment]
@webard  - Thanks for the suggestion. Let me check and will make related changes.

**Comment by webard** [comment]
I don't know if it will be faster, but instead of using `ReflectionClass` to check if `User` has `HasApiTokens` trait, You can use Laravel helper `trait_uses_recursive` (probably do the same under the hood).

**Comment by joskfg** [comment]
I have an issue here because I have two user clases, one in auth.providers.users and another in auth.providers.trainers and I want to track the Trainer users.

**Comment by vc-vinay** [comment]
Hi @joskfg ,

we designed the active session package with a general use case in mind, which typically revolves around tracking active users in the application.

However, we understand that there are scenarios where users might have different roles or classes beyond the standard User model. To address this limitation and cater to a wider range of use cases, we encourage you to submit a pull request (PR) that introduces support for tracking multiple user classes or allows for customization to specify which user class to track.
